<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 43" tests="1" total_time="Finished in: 0.00 secs."/>
<test location="&lt;unable to get file&gt;" status="error" test="tests.Test_Case1.Test_Case1 &lt;setUpClass&gt;" time="">
<stdout/>
<stderr><![CDATA[TypeError: unbound method setUpClass() must be called with Test_Case1 instance as first argument (got nothing instead)
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="MatchMe tests"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
