<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 28" tests="1" total_time="Finished in: 74.63 secs."/>
<test location="C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\generics\BaseTest.py" status="error" test="BaseTest.test_01" time="">
<stdout><![CDATA[Waiting for scene to be MainMenu...
Current scene is MainMenu
Waiting for element button "information"...
Element button "information" found at x:80 y:1157 mobileY:123
Waiting for element Information Pop-up...
Element Information Pop-up found at x:360 y:643 mobileY:637
Waiting for element Close...
Element Close found at x:671 y:939 mobileY:341
Waiting for element Play...
Element Play found at x:360 y:287 mobileY:993
Waiting for scene to be Map...
Current scene is MainMenu
Waiting for scene to be Map...
Current scene is MainMenu
Waiting for scene to be Map...
Current scene is MainMenu
Waiting for scene to be Map...
Current scene is MainMenu
Waiting for scene to be Map...
Current scene is Map
Waiting for element Base...
Element Base found at x:151 y:1216 mobileY:64
Waiting for element Close...
Element Close found at x:671 y:1924 mobileY:-644
]]></stdout>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\generics\BaseTest.py", line 54, in test_01
    self.scene2.S2_flow_01()
  File "C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\scenes\Scene2.py", line 27, in S2_flow_01
    self.scene2.clickLives()
  File "C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\workflow\Scene2Tasks.py", line 20, in clickLives
    self.altdriver.wait_for_element('Close').tap()
  File "C:\Python27\lib\site-packages\altunityrunner\runner.py", line 60, in tap
    self.appium_driver.tap([[float(self.x), float(self.mobileY)]], durationInSeconds * 1000)
  File "C:\Python27\lib\site-packages\appium\webdriver\webdriver.py", line 249, in tap
    action.perform()
  File "C:\Python27\lib\site-packages\appium\webdriver\common\touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: The coordinates provided to an interactions operation are invalid.

]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="MatchMe BaseTest.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
